### ISSUE TITLE
fbconnect tab in user page

### ISSUE THREAD

**Issue by joetsuihk** [vectoroc/fbconnect#2]
in hook_menu(), user/%user/fbconnect

the page arg should be arg(2) instead of array(1), so admin can access another user's fb profile settings and change the user's.

you access another user's fbconnect tab and will reproduce.

**Comment by vectoroc** [comment]
do you mean array(2) instead of array(1). because arg(2) is incorrect here

**Comment by joetsuihk** [comment]
no, i mean arg(2): http://api.drupal.org/api/function/arg/6, so the user id of current viewing user is passed, instead of current login user

why arg(2) is not correct?

**Comment by vectoroc** [comment]
arg(0) == 'user'
arg(1) == %user placeholder
array(1) in hook_menu means arg(1)

**Comment by joetsuihk** [comment]
mm...true, sorry abt that.
